// Extra accepted answers per country code, beyond the generated en/fr names.
// Values must already be in normalize() form: lowercase, no diacritics,
// single-spaced. Keep these unambiguous - an alias that fits two countries
// causes wrong answers to be accepted.
export const ALIASES: Record<string, string[]> = {
  US: ["usa", "us", "united states", "america", "etats unis", "etats unis d amerique"],
  GB: [
    "uk", "britain", "great britain", "england", "angleterre",
    "grande bretagne", "royaume uni de grande bretagne",
  ],
  NL: ["holland", "hollande", "the netherlands", "pays bas"],
  AE: ["uae", "emirates", "emirats", "emirats arabes unis"],
  CZ: ["czechia", "tchequie", "czech republic", "republique tcheque"],
  MM: ["burma", "birmanie"],
  CD: [
    "drc", "rdc", "congo kinshasa", "congo drc",
    "democratic republic of congo", "republique democratique du congo",
  ],
  CG: ["congo", "congo brazzaville", "republic of the congo", "republique du congo"],
  CI: ["ivory coast", "cote d ivoire"],
  RU: ["russian federation", "federation de russie"],
  KR: ["republic of korea", "coree"],
  KP: ["dprk", "north korea", "coree du nord"],
  CN: [
    "peoples republic of china", "republique populaire de chine", "prc",
  ],
  IR: ["islamic republic of iran"],
  LA: ["lao", "lao peoples democratic republic"],
  SY: ["syrian arab republic", "syrie"],
  TZ: ["united republic of tanzania", "republique unie de tanzanie"],
  MD: ["moldova republic of", "republic of moldova"],
  MK: ["macedonia", "the republic of north macedonia", "fyrom"],
  FM: ["federated states of micronesia", "micronesie"],
  GM: ["the gambia", "republic of the gambia"],
  SZ: ["swaziland"],
  CV: ["cape verde", "cabo verde", "cap vert"],
  TL: ["east timor", "timor oriental", "timor leste"],
  VN: ["viet nam"],
  BN: ["brunei darussalam"],
  BO: ["plurinational state of bolivia", "etat plurinational de bolivie"],
  VE: ["bolivarian republic of venezuela"],
  TR: ["turkey", "turkiye"],
  ST: ["sao tome", "sao tome and principe", "sao tome et principe"],
  BA: ["bosnia", "bosnie", "bosnia and herzegovina", "bosnie herzegovine"],
  CF: ["central african republic", "republique centrafricaine"],
  DO: ["dominican republic"],
  KN: ["st kitts and nevis", "saint kitts and nevis"],
  VC: ["st vincent and the grenadines", "saint vincent and the grenadines"],
};
